### ISSUE TITLE
wrong duration and some artrifact added

### ISSUE THREAD

**Issue by luca2125** [hzwer/arXiv2020-RIFE#102]
Hi,

I have triied your frame interpoletion tool "Flowframes" i find it better than other similar (more fast and better result) but there are some compromise:

1 The file output duration is wrong (1:22 minutes original, 1.18 minutes output).
2 Add diffents glitch in the first 10 seconds and others in other parts:

Here my test files:

https://drive.google.com/drive/folders/1_cwBnK8h6mtn0eMTvUZyYLJEnPoWV3KJ?usp=sharing

can you check please ?

Thanks !

**Comment by n00mkrad** [comment]
1) This is the repo for the official code. This is the Flowframes repo: https://github.com/n00mkrad/flowframes

2) The output duration is not wrong. The input file is 1:18. Some video players show 1:22 which is not correct, it's a misreported value due to the ancient format of the video. This can be proven by multiplying the frame count with the framerate.

3) You can avoid scene cut glitches by using a lower value for "Don't Interpolate Scene Changes". 0.15 works well.

I gave it a shot myself:

https://user-images.githubusercontent.com/61149547/107095228-af006d80-6808-11eb-8619-e45f2c9ac47f.mp4
