### ISSUE TITLE
Convert anime to 60FPS without changing video length.

### ISSUE THREAD

**Issue by JoseEscobar14** [hzwer/arXiv2020-RIFE#163]
How do I convert an anime video from 23.976 to 60fps without changing the length of the video and not erasing the audio from the video?
I have tried the x2 interpolation and then with a video editor I exported it to 60fps but the fluidity of the video was not very noticeable.
So I tried putting this: --exp = 2 --fps = 60
but I was slowing down the video.
Currently I don't have a computer, therefore I am using google colab.

**Comment by n00mkrad** [comment]
This is not possible, you need to interpolate to 96 FPS then downsample to 60 using ffmpeg etc.

**Comment by itsTyrion** [comment]
Why are you even trying that? It completely ruins aspects like timing and easing (because that's what computers try to do: Connect the dots as clean and efficient as possible. Not to mention the artifacts.

The lack of fluidity you mentioned is probably a 2D animation thing: It's not uncommon to keep one frame for the interval of 2 frames. It's called animating on twos, so you might have a video that's constantly jumping between 12 and 48/96 FPS.

So you either
- keep it at 48 FPS if it's good enough
- OR you interpolate it to 96 FPS and render it out in 60 (this will probably cause extra stutter because 96 is not evenly divisable by 60, meaning that the number of frames that need to be dropped is not constant)
- OR leave it as is if the Anime uses a lot of animation on twos, because you will not have a smooth video, but a smoothed stutter

**Comment by Kafu-Yukimura** [comment]
23.976 is similar to 24, so it is 48 fps at x2.
Usually it seems to sample a lot at 96 fps, but the framerate is more important than fps (frame per second) for the smoothness of the animation.
Therefore, after making the video to 192fps given a multiple of x8, you need to use the `-framerate 192 -vf fps=1920/32` command in ffmpeg.

**Comment by JoseEscobar14** [comment]
> 23,976 es similar a 24, por lo que es 48 fps en x2.
> Normalmente, los usuarios muestrean a 96 fps y convierten a 60 fps, pero la velocidad de fotogramas es más importante que los fps (fotogramas por segundo) para la suavidad de la animación.
> Por lo tanto, después de hacer el video a 192 fps dado un múltiplo de x8, debe usar el `-framerate 192 -vf fps=1920/32`comando en ffmpeg.

thanks bro if it worked for me ^^
 I must say that you notice a better fluidity in the video.
