### ISSUE TITLE
Request 8K video support.

### ISSUE THREAD

**Issue by Kafu-Yukimura** [hzwer/arXiv2020-RIFE#187]
I know that RIFE does not work with 8K video yet, but I would like to know if 8K support is possible through UHD Mode in the future.

**Comment by hzwer** [comment]
Currently RIFE needs to perform backward warping on the original image, which may be a GPU memory bottleneck. From an engineering perspective, we may reduce the data bit width (float32=>float16) to save GPU memory. I am currently writing a new training framework, and hope that in the future the community can reproduce RIFE more easily so that they can try these improvements.

**Comment by Kafu-Yukimura** [comment]
In UHD Mode, is it not a compatibility issue with 8K video, but a lack of memory?

**Comment by hzwer** [comment]
Yes，I have test some 4K video. We should inference optical flow in suitable resolution scale because of the training dataset. I wrote a adaptive scale in https://github.com/hzwer/Practical-RIFE.

**Comment by Kafu-Yukimura** [comment]
Ok. But I use a tool based on rife-ncnn-vulkan, so I guess I'll have to wait for it to be updated.
I can't modify the scale value in ncnn-vulkan right now.
