### ISSUE TITLE
Support HD videos

### ISSUE THREAD

**Issue by hzwer** [hzwer/arXiv2020-RIFE#42]
I found that the effect of the current model on small images is much better than on 1080p video. I plan to release a new model for large-resolution videos. Under the premise of the same processing speed, the results of 1080p and 2K video can be significantly improved (preliminary verification).

**Comment by hzwer** [comment]
check https://github.com/hzwer/arXiv2020-RIFE/issues/41#issuecomment-737651979, the improvement is incredible.

**Comment by StoneCypher** [comment]
I would like to know how you made the improvements for 720 vs 1080, and what it would take to do a good job with 4k, please

**Comment by hzwer** [comment]
> I would like to know how you made the improvements for 720 vs 1080, and what it would take to do a good job with 4k, please

Hi, first we increase the receptive field of our model. Second we add resize augmentation during training. 

I tested some 4K scenarios, which is much better than before. If you're not satisfied with the results of your video. Can you upload a 4K short clip or several PNG frames to Google drive? I'm very glad to try to improve the model.

**Comment by StoneCypher** [comment]
I haven't tried it yet.  The hardware just showed up yesterday 😅  I'm going to learn `conda` tonight

I'm new to this stuff.  I apologize if that read like I had results that I wasn't happy with; I didn't mean that.  I haven't any results at all yet.

What I meant was, you seemed to be starting support for HD, and since my interest was 4k, I was wondering if more stuff needed to be done for that, and how I could pitch in.

I will do my best to follow your instructions with regards to google drive.  Please understand that I didn't mean I have any bad results yet.  I'm just trying to prepare :)

**Comment by StoneCypher** [comment]
That thing where we found the `python` issue at roughly the same time?

I don't speak python yet 😁

**Comment by hzwer** [comment]
I tested some 4K videos and the results are acceptable. In fact, my reply is basically from Google Translate, so the emotional expression may be confusing :)

**Comment by StoneCypher** [comment]
Are there things that I can do to support the 4k process?

**Comment by hzwer** [comment]
If you have time, you can look for some unsatisfactory 4k interpolated video for me to debug.

**Comment by StoneCypher** [comment]
Suppose I find something.  What is the ideal length of sample?  Do you want five seconds, five minutes, five frames?

**Comment by hzwer** [comment]
Five seconds and five frames are both OK.
