### ISSUE TITLE
Image output Uncompressed? 

### ISSUE THREAD

**Issue by Anafeyka** [hzwer/arXiv2020-RIFE#72]
If i use --png. They are compressed at output.

1 freme 4K video uncompressed = 28mb
1 freme 4k vid_out = 3,65mb

And you can see that frames are very compressed.
Is there a lossless interpolation?

For the video, the same thing. Even if I change the codec to ('I','4','2','0'). the video will be writed in uncompressed form but the frames that will be writed will be compressed.

I can't figure it out yet. Is this a problem of skvideo & opencv or is this what we get from the model?

**Comment by TheHardew** [comment]
1 frame 3840x2160 yuv420p uncompressed = 23,73 MiB (because of chroma subsampling, luma plane is 3840x2160 and 2 chroma planes are 1920x1080)

Png and bmp store image in rgb so there is no chroma subsampling, it would be good if the developers confirmed if the program outputs yuv420 or rgb or maybe yuv444.

png is lossless compression. I'm not familiar with opencv, but from the documantation I think you can switch
`cv2.imwrite('vid_out/{:0>7d}.png'.format(cnt), item[:, :, ::-1])` to `cv2.imwrite('vid_out/{:0>7d}.bmp'.format(cnt), item[:, :, ::-1])` while using `--png` flag if you don't want to waste cpu time on compression. `('I','4','2','0')` is also ok. Be careful, it can quickly fill up your disk and maybe even shorten it's lifespan, if you are using an ssd.

**Comment by Anafeyka** [comment]
@TheHardew 
This solution also occurred to me. But it doesn't solve the problem.
An example of comparing the original frames and what we get at the output.
https://imgsli.com/MzM5NzU

I am inclined to believe that these artifacts appear as a consequence of interpolation

**Comment by TheHardew** [comment]
I think you are comparing an input frame and a frame interpolated from the 2 input ones?

When using the script to interpolate between images, the original frames, when output, are 100% identical to the ones which were provided, the interpolated ones are worse. By skimming through the code I think the video interpolation script also copies the input frames to the encoder losslessly, so if you use I420, compression should not be a problem. I'm guessing that's a problem with the model, not the script, since it has to interpolate a whole new frame, not just the moving objects? Also, the interpolated frames appear to be darker, on my machine too.

**Comment by Anafeyka** [comment]
@TheHardew 
I'm comparing non-interpolated frames.
But then the question remains open. Why when I build this repository source: [https://github.com/nihui/rife-ncnn-vulkan](https://github.com/nihui/rife-ncnn-vulkan)
I get undistorted images in the output. there the implementation as far as I understand is the same as here.

**Comment by StoneCypher** [comment]
It would be helpful if you could post a distorted and a not distorted full frame, instead of a side-by-side half, so that we could compare them to see the distortion you're worried about

It would also be helpful if that frame was of something with clear characteristics, like buildings, machines, faces, or wood, to make the distortion more obvious

**Comment by Anafeyka** [comment]
@StoneCypher 
https://drive.google.com/file/d/1DWcVBlDBiH-vK60uEIbHS696a_ota9AP/view?usp=sharing

**Comment by StoneCypher** [comment]
The `in` and `out` photos in that zip are pixel-identical, other than that in is 48bpp and out is 24bpp 

No monitor on the market can show >24bpp.  ***If you're seeing a difference between those two images, you're imagining it.***

If you want to prove it to yourself, set up an A B X test.  X is `in`.  A is also `in`.  B is `out`.

Now, show X and then flip a coin and show A or B.  Try to guess whether it's A or B.  Standard is 15 attempts, and you need to get 11 right (you'd get 7.5 by flipping a coin) to be outside dumb luck.

**Comment by chappjo** [comment]
If you want to make the video interpolation lossless just change the line:
`fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')`
to:
`fourcc = cv2.VideoWriter_fourcc('H', 'F', 'Y', 'U')`
or another lossless equivalent. You can find the fourcc codes on [this](https://www.fourcc.org/codecs.php) page. Beware that lossless videos have very large file sizes.

By default RIFE outputs a file with the video codec MPEG-4, instead of a more modern codec like MPEG-4 AVC/H264 or H265/HEVC.

**Comment by chappjo** [comment]
@StoneCypher

Monitors are available that can display >24 bit colour. Anything [HDR 500](https://displayhdr.org/#tab-500) or above "Requires 10-bit image processing".

**Comment by Anafeyka** [comment]
@chappjo 
The point is that it doesn't matter which codec is used inference_video.py always outputs 8 bit depth
i made 1 more example where it's more obvious!
[https://drive.google.com/file/d/1_ZAp0lW9aaNBrNheHvKkv2KP8zrnx0-a/view?usp=sharing](https://drive.google.com/file/d/1_ZAp0lW9aaNBrNheHvKkv2KP8zrnx0-a/view?usp=sharing)
